site_name: Laser Prediction Documentation

nav:
  - Home: index.md
  - Prerequisites: prerequisites.md
  - Installation: installation.md
  - Usage: usage.md
  - Model Usage: model.md

plugins:
  - mkdocstrings

theme: readthedocs