site_name: Laser Prediction Documentation
nav:
  - Home: index.md
  - Getting Started:
      - Prerequisites: docs/prerequisites.md
      - Installation: docs/installation.md
      - Usage: docs/usage.md
  - Model Usage: model.md

plugins:
  - mkdocstrings

theme: readthedocs