site_name: Laser Prediction Documentation
nav:
  - Home: index.md
  - Getting Started:
      - Prerequisites: docs/prerequisites.md
      - Installation: docs/installation.md
  - Model Usage: model.md
  - Notebooks: notebooks.md
  - API Reference: api-reference.md
  - Contributing: contributing.md
  - License: license.md
  - Contact: contact.md

plugins:
  - mkdocstrings

theme: readthedocs